/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedCriarRouteImport } from './routes/_authenticated/criar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMeusPostsRouteImport } from './routes/_authenticated/meus-posts'
import { Route as AuthenticatedPostPostIdRouteImport } from './routes/_authenticated/post.$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCriarRoute = AuthenticatedCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusPostsRoute = AuthenticatedMeusPostsRouteImport.update({
  id: '/meus-posts',
  path: '/meus-posts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostPostIdRoute = AuthenticatedPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meus-posts': typeof AuthenticatedMeusPostsRoute
  '/post/$postId': typeof AuthenticatedPostPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meus-posts': typeof AuthenticatedMeusPostsRoute
  '/post/$postId': typeof AuthenticatedPostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/_authenticated/criar': typeof AuthenticatedCriarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/meus-posts': typeof AuthenticatedMeusPostsRoute
  '/_authenticated/post/$postId': typeof AuthenticatedPostPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar-conta'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/criar'
    | '/dashboard'
    | '/meus-posts'
    | '/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar-conta'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/criar'
    | '/dashboard'
    | '/meus-posts'
    | '/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/criar-conta'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/_authenticated/criar'
    | '/_authenticated/dashboard'
    | '/_authenticated/meus-posts'
    | '/_authenticated/post/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CriarContaRoute: typeof CriarContaRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/criar': {
      id: '/_authenticated/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AuthenticatedCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-posts': {
      id: '/_authenticated/meus-posts'
      path: '/meus-posts'
      fullPath: '/meus-posts'
      preLoaderRoute: typeof AuthenticatedMeusPostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post/$postId': {
      id: '/_authenticated/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof AuthenticatedPostPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCriarRoute: typeof AuthenticatedCriarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeusPostsRoute: typeof AuthenticatedMeusPostsRoute
  AuthenticatedPostPostIdRoute: typeof AuthenticatedPostPostIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCriarRoute: AuthenticatedCriarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeusPostsRoute: AuthenticatedMeusPostsRoute,
  AuthenticatedPostPostIdRoute: AuthenticatedPostPostIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CriarContaRoute: CriarContaRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
